### ISSUE TITLE
Error in running dca

### ISSUE THREAD

**Issue by mkrzak** [theislab/dca#14]
Hello,

I have a problem when running the "dca matrix.csv results":
`  File "/usr/local/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/local/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'`

I tried one solution: sudo apt-get install tk-dev , but didnt work out.

Is there anyone who knows how to solve the problem with this module ?

Best,
Monika

**Comment by gokceneraslan** [comment]
Hi Monika,

Thanks for the report. This seem matplotlib related. Can you try `sudo apt-get install python3-tk`?

**Comment by mkrzak** [comment]
Hello,
I installed python3-tk but getting the same error..I have two versions of python , I installed on both tkinter module.

**Comment by gokceneraslan** [comment]
`python3 -c "import matplotlib.pyplot"` command also doesn't work, right? Then it's a python/tk issue. I recommend using [Anaconda](https://www.anaconda.com/download/) to avoid these issues.

**Comment by gokceneraslan** [comment]
Alternatively, you can switch to `Agg` backend of matplotlib. Create `~/.config/matplotlib/matplotlibrc`file and write `backend : Agg` in it, as described [here](https://stackoverflow.com/questions/4930524/how-can-i-set-the-backend-in-matplotlib-in-python).
