### ISSUE TITLE
scale data

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/dca#23]
Dear,
In DCA tutorial, there is no sc.pp.scale(adata) between sc.pp.log1p(adata) and sc.pp.pca(adata), which is present in  Scanpy’s reimplementation of Seurat (https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html).

Is it necessary to use sc.pp.scale()?

**Comment by wangjiawen2013** [comment]
And, what does the paramerter "batchnorm" mean ?

**Comment by gokceneraslan** [comment]
`sc.pp.scale` is not necessary, `sc.pp.pca` does zero-mean normalization. About concatenating batches, note that DCA does not perform any batch correction. Assuming there is no batch effect, I'd concatenate first and then apply DCA.
