### ISSUE TITLE
cannot recognize fluidigm RNA-seq raw counts 

### ISSUE THREAD

**Issue by Winnie09** [theislab/dca#25]
Hello author,

I was running dca on RNA-seq raw counts data generated by fluidigm. However, the programme is terminated with error message as follows:
AssertionError: Make sure that the dataset (adata.X) contains unnormalized count data.

I double check the input and am sure that it is an unnormalized count matrix (gene by cell).  May I know your suggestions? Thanks!

**Comment by kmuench** [comment]
Hello,
Did you find a resolution to this? I am having a similar issue.

**Comment by alikhuseynov** [comment]
same issue for me, I ended up using [SAVERX](https://github.com/jingshuw/SAVERX) see comments on [install issue](https://github.com/jingshuw/SAVERX/issues/16)
thx

**Comment by gokceneraslan** [comment]
I added a new command line argument to skip the check e.g. `dca --nocheckcounts`
