### ISSUE TITLE
Tensorflow version?

### ISSUE THREAD

**Issue by alexQiSong** [theislab/dca#33]
Hi,

I installed dca through conda and tried to call dca by scanpy function `sc.external.pp.dca()`. But then I got the error message from tensorflow. Below is the code:
```python
import numpy as np
import pandas as pd
import scanpy as sc
adata = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/',  var_names='gene_ids', cache=True)
result = sc.external.pp.dca(adata)
```

And the error message I got is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/udd/spqis/.conda/envs/scanpy/lib/python3.7/site-packages/scanpy/preprocessing/_dca.py", line 154, in dca
    return_model=return_model)
  File "/udd/spqis/.conda/envs/scanpy/lib/python3.7/site-packages/dca/api.py", line 149, in dca
    tf.set_random_seed(random_state)
AttributeError: module 'tensorflow' has no attribute 'set_random_seed'
```
My guess is that conda got me a tensorflow version that is incompatible with dca. Can this be fixed? Thank you!

**Comment by kmuench** [comment]
Hello, I am having this issue as well. Were you able to find a solution? I believe I'm using Python 3.7, tensorflow v2.1.0

**Comment by kmuench** [comment]
Another follow-up - although the code runs with the older version of tensorflow, I get a lot of messages like:

2020-02-10 13:37:18,714 [WARNING] From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/dca/train.py:41: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.


Will DCA be updated to use tensorflow v2.1.0?

**Comment by france-hub** [comment]
I am having the same issue. Were you able to proceed with your analysis after installing tensorflow 1.15?

**Comment by kmuench** [comment]
Yes, I was able to run through the rest of the tutorial - just with the extra error messages.

**Comment by Fronttooth** [comment]
> I am having the same issue. Were you able to proceed with your analysis after installing tensorflow 1.15?

Yes, as kmuench commented, tensorflow=1.15 works for me as well. Good luck with it.

**Comment by france-hub** [comment]
> Yes, I was able to run through the rest of the tutorial - just with the extra error messages.

Thank you!

**Comment by france-hub** [comment]
> > I am having the same issue. Were you able to proceed with your analysis after installing tensorflow 1.15?
> 
> Yes, as kmuench commented, tensorflow=1.15 works for me as well. Good luck with it.

Thank you too!
