### ISSUE TITLE
ImportError: cannot import name 'stacked_violin'

### ISSUE THREAD

**Issue by chenziyi** [theislab/dca#42]
I just install it with pip3 install dca in python 3.6.2. Then run it with a commandline "dca GSM3892344.expres.ensemble.csv ./test". ImportError: cannot import name 'stacked_violin' Could you please whether this is because the scanpy version not compatible with the dca installed here.

**Comment by lylamha** [comment]
I had the same issue. Basically, I had to downgrade scanpy to version 1.5.1 with `pip install --upgrade scanpy==1.5.1`.
Then I had issues with tensorflow and keras. At the end I use tensorflow version 1.15 and keras version 2.3.0 and it works now.

**Comment by chenziyi** [comment]
Thanks for your kindly reply.

**Comment by a-munoz-rojas** [comment]
Also had the same issue. It seems that the problem is due to importing scanpy the "old way":
In the dca/api.py file, line4:
`import scanpy.api as sc`

Should be using `import scanpy as sc`
