### ISSUE TITLE
Some questions about DCA implementation

### ISSUE THREAD

**Issue by HelloWorldLTY** [theislab/dca#52]
Hi, I wonder why the ZINB loss implementation and NB loss implementation are different for codes and theoretical definitions. 

I notice that in the paper, NB and ZINB are defined as:
![image](https://user-images.githubusercontent.com/43333475/165430844-0b629fe9-812f-4b52-8c54-b11f37bada74.png)
However, I found that in the part of the codes, ZINB loss's NB is defined as:
![image](https://user-images.githubusercontent.com/43333475/165430896-2ba1b753-917a-4cea-99ae-b8fb254dbb2a.png)
Therefore, I wonder where is gamma function? Thanks a lot!

**Comment by valentinwust** [comment]
ZINB inherits from NB and only implements the difference, the gamma functions get called via the NB loss as:
`nb_case = super().loss(y_true, y_pred, mean=False) - tf.math.log(1.0-self.pi+eps)`

**Comment by gokceneraslan** [comment]
That's right
