### ISSUE TITLE
Mode 'full' does not return the correct latent representation

### ISSUE THREAD

**Issue by valentinwust** [theislab/dca#53]
In mode 'full', the original data is overwritten with
`adata.X = self.model.predict({'count': adata.X, 'size_factors': adata.obs.size_factors})`
before the latent representation is created using:
`adata.obsm['X_dca'] = self.encoder.predict({'count': adata.X, 'size_factors': adata.obs.size_factors})`
"X_dca" therefore does not contain the accurate latent representation if this mode is used.

**Comment by gokceneraslan** [comment]
Thanks! Should be correct now.
